### ISSUE TITLE
Unable to build any image that's been pulled

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#406] opened 2024-04-29 15:29 UTC
With https://github.com/containers/podman-desktop-extension-bootc we always have `--local` present, unless you have locally built it...

This no longer works, for example, using our example image `podman pull quay.io/bootc-extension/httpd`

To replicate:

```
podman pull quay.io/bootc-extension/httpd
```

Then use bootc-image-builder:

```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type raw --target-arch arm64 \
    --local \
    quay.io/bootc-extension/httpd
```

Will fail with:

```
▶ podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type raw --target-arch arm64 \
    --local \
    quay.io/bootc-extension/httpd
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob sha256:d2d335e3ff36eb2c14653641ee5af2db67eaa148b21142946b4c7f2221bf9bf7
Copying blob sha256:d1d88850a0e9b4b8d8f3608b8ea75570f678c421aea4235f5da2d980a0c8079a
Copying blob sha256:1ff5b3d378b54a54652cc50bee9ff5bac849d28efe63a2f8ab0d0f1853110e57
Copying config sha256:7e40d33bb69963f79d289b9a93822dac304f12c8c557dbb9db901b04fd2e0ab3
Writing manifest to image destination
Generating manifest manifest-raw.json
Error: cannot build manifest: cannot get container size: failed inspect image: exit status 125, stderr:
time="2024-04-29T15:24:41Z" level=error msg="Refreshing container 4c2b2770dc407b555b6a3e4e49facb7fc99006890a07ef028b505a3d14e6d150: acquiring lock 0 for container 4c2b2770dc407b555b6a3e4e49facb7fc99006890a07ef028b505a3d14e6d150: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Refreshing volume 13853475af3df417161e372528084734fec12906c84d1d1fc012ec37f9829c53: acquiring lock 1 for volume 13853475af3df417161e372528084734fec12906c84d1d1fc012ec37f9829c53: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Refreshing volume 03e1c02c5913782735c076a1426690817e33f12b56de4209adff1e5ffeb49820: acquiring lock 2 for volume 03e1c02c5913782735c076a1426690817e33f12b56de4209adff1e5ffeb49820: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Unable to write system event: \"write unixgram @31512->/run/systemd/journal/socket: sendmsg: no such file or directory\""
Error: size for layer "c00786d2fc105237e11e417af39b9a0b35c83fd59d3f06a91546b48b81225109" is unknown, failing getSize()

2024/04/29 15:24:41 error: cannot build manifest: cannot get container size: failed inspect image: exit status 125, stderr:
time="2024-04-29T15:24:41Z" level=error msg="Refreshing container 4c2b2770dc407b555b6a3e4e49facb7fc99006890a07ef028b505a3d14e6d150: acquiring lock 0 for container 4c2b2770dc407b555b6a3e4e49facb7fc99006890a07ef028b505a3d14e6d150: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Refreshing volume 13853475af3df417161e372528084734fec12906c84d1d1fc012ec37f9829c53: acquiring lock 1 for volume 13853475af3df417161e372528084734fec12906c84d1d1fc012ec37f9829c53: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Refreshing volume 03e1c02c5913782735c076a1426690817e33f12b56de4209adff1e5ffeb49820: acquiring lock 2 for volume 03e1c02c5913782735c076a1426690817e33f12b56de4209adff1e5ffeb49820: file exists"
time="2024-04-29T15:24:41Z" level=error msg="Unable to write system event: \"write unixgram @31512->/run/systemd/journal/socket: sendmsg: no such file or directory\""
Error: size for layer "c00786d2fc105237e11e417af39b9a0b35c83fd59d3f06a91546b48b81225109" is unknown, failing getSize()
```

HOWEVER, if you build the image locally, it works:

```
podman build -t foobar .
```

```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type raw --target-arch arm64 \
    --local \
    localhost/foobar
Generating manifest manifest-raw.json
DONE
Building manifest-raw.json
starting -Pipeline source org.osbuild.containers-storage: 785287829930c6d7180fd0fcf9bef28e4730a5d9b707910cffa6d87508f67105
Build
  root: <host>
Pipeline build: 90f3ce5c5a2daf5bdbdb6bfd7e108d7b9cb06084166d68238134cedaae8bf655
Build
  root: <host>
  runner: org.osbuild.fedora38 (org.osbuild.fedora38)
org.osbuild.container-deploy: c38736917b5dc31f044e3432300c32bbc08fabcc18c7086d4d66c977d3aa6c50 {}
Getting image source signatures
Copying blob sha256:159348fa9cfbb75c5cb57e9fac24b9f28477412149e901bdadb909bfaeb84dad
Copying blob sha256:88aab01220f9684503fb67e4ac6c7548d5503bec19e1b9935e04f86119f72f5c
Copying blob sha256:056f7f0bc1767691fa73e70c74784281da526b94477e3ec0350d803ed4188dd0
Copying blob sha256:b55fe6dcbbdbc9004759b4ad6bb2725267bfcd86ecade2ae17a842d65ac95a4a
Copying blob sha256:1398857a59385bf21b05036c99b41b3ffa2ccf989a99dd66092c8d17d927d47c
Copying blob sha256:bc6a2ddc91e10b1a426be528ef61ccab8eaddd5fbc7f294fdfc315c0439c3df8
```

**Comment by cdrage** [comment] 2024-04-29 15:41
Actually, with the image completely removed, it no longer pulls:

```
podman image ls
REPOSITORY                                TAG                IMAGE ID      CREATED         SIZE
localhost/foobar                          latest             22bca46e7457  12 minutes ago  1.66 GB
quay.io/centos-bootc/centos-bootc-dev     stream9            415e7cd7b59c  3 hours ago     1.55 GB
quay.io/centos-bootc/bootc-image-builder  latest             7e40d33bb699  9 hours ago     858 MB
quay.io/centos-bootc/bootc-image-builder  latest-1714169595  bb355d63a22a  2 days ago      858 MB
```


```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type raw --target-arch arm64 \
    --local \
    quay.io/bootc-extension/httpd
Generating manifest manifest-raw.json
Error: cannot build manifest: cannot get container size: failed inspect image: exit status 125, stderr:
time="2024-04-29T15:40:37Z" level=error msg="Refreshing container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: acquiring lock 0 for container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Refreshing volume da854bc420278ac4d868f7c9b7ea0661eb67d8b1e7735f651004044c4db5247d: acquiring lock 1 for volume da854bc420278ac4d868f7c9b7ea0661eb67d8b1e7735f651004044c4db5247d: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Refreshing volume 895e96d2f6541f57bcdef55df71d42eea70f31dec2b1c8d093b16b7140db9bcb: acquiring lock 2 for volume 895e96d2f6541f57bcdef55df71d42eea70f31dec2b1c8d093b16b7140db9bcb: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Unable to write system event: \"write unixgram @3d121->/run/systemd/journal/socket: sendmsg: no such file or directory\""
Error: quay.io/bootc-extension/httpd: image not known

2024/04/29 15:40:37 error: cannot build manifest: cannot get container size: failed inspect image: exit status 125, stderr:
time="2024-04-29T15:40:37Z" level=error msg="Refreshing container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: acquiring lock 0 for container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Refreshing volume da854bc420278ac4d868f7c9b7ea0661eb67d8b1e7735f651004044c4db5247d: acquiring lock 1 for volume da854bc420278ac4d868f7c9b7ea0661eb67d8b1e7735f651004044c4db5247d: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Refreshing volume 895e96d2f6541f57bcdef55df71d42eea70f31dec2b1c8d093b16b7140db9bcb: acquiring lock 2 for volume 895e96d2f6541f57bcdef55df71d42eea70f31dec2b1c8d093b16b7140db9bcb: file exists"
time="2024-04-29T15:40:37Z" level=error msg="Unable to write system event: \"write unixgram @3d121->/run/systemd/journal/socket: sendmsg: no such file or directory\""
Error: quay.io/bootc-extension/httpd: image not known
```

**Comment by cdrage** [comment] 2024-04-29 16:07
Another output, even with `--local` removed, it no longer pulls an image:


```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type raw --target-arch arm64 \
    quay.io/bootc-extension/httpd
Generating manifest manifest-raw.json
DONE
Building manifest-raw.json
starting -Pipeline source org.osbuild.containers-storage: 785287829930c6d7180fd0fcf9bef28e4730a5d9b707910cffa6d87508f67105
Build
  root: <host>
Pipeline build: 240e5e36840b401580a3770fba74872d69f8223340805f3572043a24aa64d316
Build
  root: <host>
  runner: org.osbuild.fedora38 (org.osbuild.fedora38)
org.osbuild.container-deploy: 9a8b9ed5b7f0915af28f19a8bde6a2f7f40a981cec2d99eba6922cb3931d476d {}
Getting image source signatures
Copying blob sha256:159348fa9cfbb75c5cb57e9fac24b9f28477412149e901bdadb909bfaeb84dad
Copying blob sha256:056f7f0bc1767691fa73e70c74784281da526b94477e3ec0350d803ed4188dd0
Copying blob sha256:b55fe6dcbbdbc9004759b4ad6bb2725267bfcd86ecade2ae17a842d65ac95a4a
Copying blob sha256:bc6a2ddc91e10b1a426be528ef61ccab8eaddd5fbc7f294fdfc315c0439c3df8
Copying blob sha256:1398857a59385bf21b05036c99b41b3ffa2ccf989a99dd66092c8d17d927d47c
Copying blob sha256:88aab01220f9684503fb67e4ac6c7548d5503bec19e1b9935e04f86119f72f5c
Copying blob sha256:ea21f664c19ce57ea2cbe3b21be9a5c4069c096e8f01afaa4fb0a14fed6918ee
Copying blob sha256:7afb53fb053f92a1555ddb31ad31773bb983ed98e012cca6e426f0c67935d976
Copying blob sha256:ed6e50b45a9355d57f5593c64d35b4e8eb7b953bc402815a201cb4986a2f7d03
Copying blob sha256:962b010d608fb3e37a22d5da75dd21a98f43e0d4a548256b8c2615132b8da976
Copying blob sha256:d14dafd0d84f06d1724f6fa5fcb78c438b53ca1e605dc3668779f5a39347e16d
Copying blob sha256:6ef238f5096277c47cac442c1cfc0091958b92391dec441d7121114f2ce9224c
Copying blob sha256:143569275e12d9aa97c245fa02a077129bf3eefa65550b588822139979dd2423
Copying blob sha256:5b8cb2c5a76d77f168728d7ec9e8140d969299446b088fd76386277d54b7622e
Copying blob sha256:1e4036afc4e15b9f799bcdf6157fdf1e788dae66c64ef6f46b411094ffc8ed25
Copying blob sha256:ff18962ccfa3557da881ec43f19936d9add6053fbaea093bf549fce38e4c82fd
Copying blob sha256:8264b77d5359dc3f95123f650aefa1d7b61f604ed879ec4fe2742fd9ee991642
Copying blob sha256:28adee727adc25437e2497271a281dfa7395894839d7cbe42ad10b6a96c839e9
Copying blob sha256:98ca63d3e1db3121180b82e806387a7337da2d445d07d315cb2fcfb525dd7247
Copying blob sha256:3f3ceec7e21248370c55f048fcbe669d5e7ad22a94da16678319830a3de97845
Copying blob sha256:312bd44fbfb86e4a31816751d39104a1bdd0e1ffed486ed5df080bcf92d99885
Copying blob sha256:03f5f2472320246b7f670da87190327701e277cb52591d49f5bc3fa6465e7218
Copying blob sha256:03f8187d462decd660e9d518a136c79c867bae006e6d4ad0e29cd476b7f81f5d
Copying blob sha256:b4d285fa41e72c1c08d693065fddaabeabb529893d391c1a68f306238bcaf899
Copying blob sha256:6afbc9f1ff554f2e93f9da5adfcf78c19079797baf26704239c9671dbdb06843
Copying blob sha256:d85d11b65e436925fb2ae85483fe3d9fe6a26d2df1253fc82d2b88e1186e61b1
Copying blob sha256:0e4b9174583041f2c4bc31e420b7614eb6bb9272d98213198d31408d2533d996
Copying blob sha256:4a90b950ef7b87cf74480bb547118e60c67f11a0be6f1ef5d6b7c5cccb628ad2
Copying blob sha256:d62c908cc2e2e6e131f07330f2a20aa290f9e929b5d9a59bec88a900e36ce47b
Copying blob sha256:0cd464dec7d8ce1e3a829526f61c64247550a0709f79006f46d19145697e1e21
Copying blob sha256:b2cd4d821498ffedc06b956d1b07f53ff8d7585816aac0bf755de926c90a5e78
Copying blob sha256:a0367a31edef38f7925acc63a8924935b1f81fe1d5eb0ca8d79107a3646697ea
Copying blob sha256:fafcf64fcc84bf1ba4177396edfd6022ed4be63044e4ad617b985a2bc769efed
Copying blob sha256:8fda0a284822f0c66b16bf57af04311fcc0ac47675d3475a6eac15349bcb047b
Copying blob sha256:20595d276e7c26092001d0172a6b8fd106e463be83ddc43ee772cf99c98e1689
Copying blob sha256:2972ed6b11ebeb23fc8caa2eef95f49f34ec577ade17b8709388d6124598822a
Copying blob sha256:83e6ac618a47cd5dde370b59c684af7e878139b301c5c32f3e38d141cfde34f5
Copying blob sha256:a49b10432533c7d1612ddf70c0e06a54f4ebe26be027f9f6b14442f7d1acc723
Copying blob sha256:d3eb22aa466d90069d019016cae45d5fd05999b3f51abd81548283d2c3357ff4
Copying blob sha256:3313c6a841ef36bc6e681ada8c1c393ca504873d65ed015ac833d1f74bc80410
Copying blob sha256:b6f72d8cf142a82591d05ec66410f205f9bdc9465d102de997bd753fce31a66e
Copying blob sha256:34be2d7389cfc8da1eeb2a6c288558161030f313a1ab8dda91880993ef5a1455
Copying blob sha256:b017ef4b8771691540296381a5c50afb1e43c7f6b41789b120764d618109f04c
Copying blob sha256:f98741e01d34831a9fa702785b8ed6f3de95ac748e4757ef4b644089eee8027d
Copying blob sha256:93a179f5197d2fb435e540bf1114ef1ad98d674c8547880fda6f7e9df4bd4ff2
Copying blob sha256:fd6c6acfc0a4b9d471a6eb426b250039bb15719728077bb3738e598ea3d2c91e
Copying blob sha256:86a1d0a84a056b2130ab95acce1c08539b9f03784c1468271cd81d7053af512e
Copying blob sha256:5c6a9b70ee943a85e8e549ea32facaa6514dee570a57af7ce4e89b9a55a7c1b5
Copying blob sha256:2323058d2ed631afeae1a57cb96d9bf2810f735c1d08e31d80fc5149eb562c56
Copying blob sha256:5e0b21051039c2e57a542424f39348315e902cdcaaa78f249157b4cd6b21e3a0
Copying blob sha256:1dc6c3529fb3e1c3c3ac46212b8589073ca6cb94465571dafab71aaf9aa487c8
Copying blob sha256:9f2af8e63a975a9b58b18fee527de9d13ad2159df491a461104be9fbe8e7e86a
Copying blob sha256:8f6bcc7dc674aecb4da0e99f31c26f599d06fccd493e29ec764bcdcd19a9d8e6
Copying blob sha256:6cf37683867820281dc0de77921774d072064c67217070f2a0f8a2ab4ed68797
Copying blob sha256:d3c6d4122f68f2470ed8e9de1fd7e84240da0d8789f0df4b312b4608b413baaf
Copying blob sha256:7c2ed65726bdcffe5f3313dcff5aff10eced87fd177de53c7d0d6aee91dcc688
Copying blob sha256:3f2e9fdf124745cebcdba6156e018e810bdd69ea1eb326140169a7057a637c38
Copying blob sha256:335542bd5817c296426f8efe4ab9a2a67663b2dab1429d67ab7bce178afea928
Copying blob sha256:1186baf7c81d140bfda2eca88c27b68ecf630249fd68a7af7f5ba2608e54d983
Copying blob sha256:449529861416a79529212f1a77b57663aa994339386308f8848c451a0938bc03
Copying blob sha256:61e095dbdc3515740cd819f1f6438cf4ed1ca648bd3f61ca414bfa70c73fd2eb
Copying blob sha256:56020de49a96a752da3fa5fa6b8de8124e5a47483d723c6fda2ca0cf4b3041b2
Copying blob sha256:33d4bdaa3e42f33b2f65c1849ee2eb6922a9c1998af87639248c52abfe378f3b
Copying blob sha256:ef947968a59b3f56dcc11be3d1364fa185f80483003c0bf7d64c0036a106c152
Copying blob sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1
Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying blob sha256:c13ac5f8514b82cdd7b272159f8e6a1b3086610ae3bdb8f5df670861ba17215c
Copying blob sha256:2def4e210a5bc3693b01fac41d740f08a09a70eb4fc09ad9db850448591d1dc3
Copying blob sha256:3e7c42c2626a21f7e6fccedd9b85655169dd3dfc3004ee1458dfd25311727d43
Copying blob sha256:43c505bfc9ec4e53160db792ab530fb3e2ce8d35307290c9e2b2a34bba30922f
time="2024-04-29T16:06:05Z" level=fatal msg="writing blob: storing blob to file \"/var/tmp/container_images_storage1826090969/67\": happened during read: Digest did not match, expected sha256:2def4e210a5bc3693b01fac41d740f08a09a70eb4fc09ad9db850448591d1dc3, got sha256:ace5ca2ca4b2fb99b333e6f64bf4c4eb2396aa87f2daff7c8387e6743571e8a7"
time="2024-04-29T16:06:06Z" level=error msg="Unable to write system event: \"write unixgram @1f5e5->/run/systemd/journal/socket: sendmsg: no such file or directory\""
Error: tmp-container-deploy-58662978976439: image not known
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 50, in main
    subprocess.run(
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['skopeo', 'copy', 'containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]22bca46e7457fdf3e83f7b4f38de46581e982f315cbfb9efb56f77e7d353d5bc', 'containers-storage:tmp-container-deploy-58662978976439']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 64, in <module>
    r = main(args["inputs"], args["tree"], args["options"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 47, in main
    with contextlib.ExitStack() as cm:
  File "/usr/lib64/python3.12/contextlib.py", line 610, in __exit__
    raise exc_details[1]
  File "/usr/lib64/python3.12/contextlib.py", line 595, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/contextlib.py", line 478, in _exit_wrapper
    callback(*args, **kwds)
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'rmi', 'tmp-container-deploy-58662978976439']' returned non-zero exit status 1.

⏱  Duration: 9s
manifest - failed
Failed
Error: cannot run osbuild: running osbuild failed: exit status 1
2024/04/29 16:06:07 error: cannot run osbuild: running osbuild failed: exit status 1
```

**Comment by cgwalters** [comment] 2024-04-29 21:13
I'm trying out the same commands as you and not immediately reproducing this.  We have CI coverage for this in multiple places (including MRs to this repo) and if it was fundamentally broken we'd know.

> time="2024-04-29T15:40:37Z" level=error msg="Refreshing container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: acquiring lock 0 for container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: file exists"

Something is going wrong here in the container stack here...I wonder if there's some local corruption.    A search for that error message has a few hits...not sure if you're hitting those cases.

> time="2024-04-29T16:06:05Z" level=fatal msg="writing blob: storing blob to file \"/var/tmp/container_images_storage1826090969/67\": happened during read: Digest did not match, expected sha256:2def4e210a5bc3693b01fac41d740f08a09a70eb4fc09ad9db850448591d1dc3, got sha256:ace5ca2ca4b2fb99b333e6f64bf4c4eb2396aa87f2daff7c8387e6743571e8a7"

Also looks like local corruption.

Do you see any errors in e.g. `dmesg` on the podman machine OS?  Maybe worth trying to capture a bit more logging from that machine and doing a reset/refresh.

**Comment by cdrage** [comment] 2024-04-29 23:52
> I'm trying out the same commands as you (on both Linux and MacOS) and not immediately reproducing this. We have CI coverage for this in multiple places (including MRs to this repo) and if it was fundamentally broken we'd know.
> 
> > time="2024-04-29T15:40:37Z" level=error msg="Refreshing container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: acquiring lock 0 for container f4a5076dd740a4ddee9ddd62787c72477db8ce4af431b4384bc083d6ec9c2ff8: file exists"
> 
> Something is going wrong here in the container stack here...I wonder if there's some local corruption. A search for that error message has a few hits...not sure if you're hitting those cases.
> 
> > time="2024-04-29T16:06:05Z" level=fatal msg="writing blob: storing blob to file "/var/tmp/container_images_storage1826090969/67": happened during read: Digest did not match, expected sha256:2def4e210a5bc3693b01fac41d740f08a09a70eb4fc09ad9db850448591d1dc3, got sha256:ace5ca2ca4b2fb99b333e6f64bf4c4eb2396aa87f2daff7c8387e6743571e8a7"
> 
> Also looks like local corruption.
> 
> Do you see any errors in e.g. `dmesg` on the podman machine OS? Maybe worth trying to capture a bit more logging from that machine and doing a reset/refresh.

You are right and it's a cache issue.

Completely destroying podman machine `podman reset` and trying again gets rid of it.

However it's very intermittent it seems.. as I shortly got it again after building a bunch of manifests and long-running builds with `podman build`. Especially large images (2GB+).

**Comment by ondrejbudai** [comment] 2024-05-02 16:01
This indeed seems like an issue with underlying storage. I think I will close this one for now, because it's not clear whether this is a bib-issue, or a general podman-issue. Please, if you encounter it again, and you think it's something that bib is doing wrong, don't hesitate to re-open, or create a new ticket. I just want to keep the issue board clean. :)

**Closed by ondrejbudai** 2024-05-02 16:01 UTC
