### ISSUE TITLE
Friendlier output paths and file names

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/bootc-image-builder#247] opened 2024-03-07 12:18 UTC
File names and extensions could be more predictable and friendlier if we use image type names and the container name.
We can use the image name as a basename for the disk files and the image type as the extension.  Note that `raw` and `ami` are identical, so it might be wasteful to allow users to specify `--type raw --type ami`, build one image and copy it out as two files (which could be tens of GiB in size each).
The subdirectory in the output dir is, currently, the exported pipeline name because we take it directly from osbuild's output, but we should put it all in the same subdir (or a subdir matching the image type name).

> I want the images that are output named to match the image name or let me name the image. I was thinking that 
> `BIB quay.io/podman/foobar --type ami --type raw --type hperv --type qcow` I would end up with a directory tree of 
> 
> raw/roobar.raw
> ami/foobar.ami
> hyperv/foobar.hyperv
> qcow2/foobar.qcow2
> 
> OR
> 
> 
> image/roobar.raw
> image/foobar.ami
> image/foobar.hyperv
> image/foobar.qcow2
> 
> From a user perspective, I like the second one best, but either can be worked with.

_Originally posted by @rhatdan in https://github.com/osbuild/bootc-image-builder/pull/225#discussion_r1515163947_

**Comment by ondrejbudai** [comment] 2024-03-20 09:01
Duplicate of https://github.com/osbuild/bootc-image-builder/issues/103

**Closed by ondrejbudai** 2024-03-20 09:01 UTC
