### ISSUE TITLE
No new bib builds on quay.io since May 20th

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#503] opened 2024-06-26 16:12 UTC
See: https://quay.io/repository/centos-bootc/bootc-image-builder?tab=tags

No new builds unfortunatley for bib since last month. CI broke?

**Comment by mvo5** [comment] 2024-07-01 08:25
Sorry for the slow reply here, we immediately started to investigate and this being worked since a couple of days. We hope to have it back  up really soon.

**Comment by cgwalters** [comment] 2024-07-02 13:28
https://github.com/osbuild/bootc-image-builder/pull/508 was supposed to fix this

**Comment by deboer-tim** [comment] 2024-07-02 13:33
> #508 was supposed to fix this

Thanks for the update. 👍🏼

**Comment by ondrejbudai** [comment] 2024-07-04 12:37
We now have new builds, but they are mislabeled, @lmilbaum is working on fixing it: https://quay.io/repository/centos-bootc/bootc-image-builder?tab=tags

**Comment by lmilbaum** [comment] 2024-07-07 10:29
A new build landed two days ago - http://quay.io/centos-bootc/bootc-image-builder:latest. Please confirm it is working properly.

**Comment by lmilbaum** [comment] 2024-07-08 06:46
@shi2wei3 confirmed the new build is ok. Closing this issue as done.

**Closed by lmilbaum** 2024-07-08 06:46 UTC
