### ISSUE TITLE
Error creating ISO for fedora-bootc (base)

### ISSUE THREAD

**Issue by sigulete** [osbuild/bootc-image-builder#441] opened 2024-05-17 07:50 UTC
I created an ISO for `centos-bootc` without a problem, but when it comes to `fedora-bootc`, it shows the following error:

`No match for argument: lorax-templates-rhel error install_specs
MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: lorax-templates-rhel
Error: cannot build manifest: cannot depsolve: DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: lorax-templates-rhel
2024/05/17 07:43:15 error: cannot build manifest: cannot depsolve: DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: lorax-templates-rhel`

As I undertstand, the script is looking for a package called `lorax-templates-rhel` in the enabled repositories. But I can't find this package in any of the standard fedora repositories.

**Comment by achilleas-k** [comment] 2024-05-17 11:57
Thanks for the report.  This is a known issue.
Closing as Duplicate of #421

**Closed by achilleas-k** 2024-05-17 11:57 UTC
