### ISSUE TITLE
support s390x

### ISSUE THREAD

**Issue by cgwalters** [osbuild/bootc-image-builder#460] opened 2024-05-29 14:18 UTC
Copying the bits from here https://github.com/containers/bootc/issues/569 related to bib

It'd also be really great here to figure out how to share code w/Anaconda I'd say.

**Comment by achilleas-k** [comment] 2024-05-30 17:23
What code would we share with Anaconda for this?
Are we planning on building ISOs for s390x?

**Comment by yoheiueda** [comment] 2024-06-24 06:39
@cgwalters I raised a PR https://github.com/osbuild/images/pull/758 for this issue.

We can add a partition table for s390x after the PR gets merged.

https://github.com/osbuild/bootc-image-builder/blob/61863ff3c39da79716b0a94945b153e58a138ca6/bib/cmd/bootc-image-builder/partition_tables.go#L24-L121

**Comment by yoheiueda** [comment] 2024-07-04 06:17
@cgwalters @mvo5 @achilleas-k 

I raised a PR https://github.com/osbuild/bootc-image-builder/pull/515 to include the latest images library that includes the fix for the issue reported above.

This PR also updates the setting for `golangci-lint` CI test to suppress a false-positive lint error.

**Comment by yoheiueda** [comment] 2024-07-19 06:50
@cgwalters I created PR https://github.com/osbuild/bootc-image-builder/pull/553 to add support for s390x.

@achilleas-k For now, this PR enables QCOW2 only.

**Comment by mvo5** [comment] 2024-07-29 10:45
I would like to add some smoke tests to `bib` for this - is there a quay.io container ref for a bootc enabled s390x container that I can use for testing?

**Comment by yoheiueda** [comment] 2024-07-30 07:13
@mvo5 

I pushed `quay.io/yoheiueda/fedora-bootc:latest`. https://quay.io/repository/yoheiueda/fedora-bootc?tab=tags

I encountered several issues to build this image from the latest version of https://gitlab.com/fedora/bootc/base-images, so I manually modified the base image.  I'll report the issues later.

**Comment by mvo5** [comment] 2024-07-30 07:37
> @mvo5
> 
> I pushed `quay.io/yoheiueda/fedora-bootc:latest`. https://quay.io/repository/yoheiueda/fedora-bootc?tab=tags
> 
> I encountered several issues to build this image from the latest version of https://gitlab.com/fedora/bootc/base-images, so I manually modified the base image. I'll report the issues later.

Thank you! I updated https://github.com/osbuild/bootc-image-builder/pull/566 to point to this container ref. When testing this (or clicking on the link above) I get a " Repository not found " error though, are these images maybe not set to public yet?

**Comment by yoheiueda** [comment] 2024-07-30 07:58
@mvo5 Sorry. I made it public.

**Comment by cgwalters** [comment] 2024-07-30 11:36
`quay.io/fedora/fedora-bootc:41` is built for all 4 primary Fedora architectures since https://pagure.io/fedora-iot/pungi-iot/pull-request/78

**Comment by yoheiueda** [comment] 2024-07-30 14:42
@cgwalters Thank you for the info. I tested `quay.io/fedora/fedora-bootc:41` on my local environment, and it works fine.

Will the support of the additional architectures eventually come to fedora-40, centos-stream-9, and rhel-9?

BTW, I can't reproduce the issues I reported above any more in my environment, so please forgot it.

**Comment by cgwalters** [comment] 2024-08-01 20:56
> Will the support of the additional architectures eventually come to fedora-40, centos-stream-9, and rhel-9?

https://gitlab.com/fedora/bootc/tracker/-/issues/15 will track the fedora/c{9,10s} efforts, and since CentOS Stream *is* RHEL it covers that too implicitly.

**Comment by yoheiueda** [comment] 2024-09-06 05:18
@cgwalters Could you please close this issue unless any more change is necessary in this repo to support s390x? I understand that enablement of public container image builds are being tracked by the GitLab issue you mentioned.

**Comment by cgwalters** [comment] 2024-09-06 12:50
Thanks for all the work on this everyone!

**Closed** 2024-09-06 12:50 UTC
Labels: enhancement
